### ISSUE TITLE
Existing Keybord crash

### ISSUE THREAD

**Issue by aswinjoseph91** [FleksySDK/PredictiveTextSDK#5]
Hello,
We are trying to integrate your SDK into our existing keyboard application. 
After installing the library using Swiftpackagemanager (https://github.com/FleksySDK/PredictiveSDK-iOS), the keyboard crashes, even without using that library in the code. 
Is there any additional config we should use?
All the necessary steps from your documentation (https://docs.fleksy.com/core-sdk/ios/) is followed. But we receive this error as follows,

dyld[994]: Library not loaded: @rpath/FleksyLibModule.framework/FleksyLibModule
  Referenced from: <85517271-BE56-38ED-9BF3-67ADD1763ADD> /private/var/containers/Bundle/Application/6E41486B-B6CD-44CD-AFB9-18305781F16D/SampleKeyboard.app/PlugIns/SampleKeyboardApp.appex/SampleKeyboardApp
  Reason: tried: '/Users/mathew/Library/Developer/Xcode/DerivedData/SampleKeyboard-cwpdwgsjygjypaaaunncgzynbaby/Build/Products/Debug-iphoneos/PackageFrameworks/FleksyLibModule.framework/FleksyLibModule' (no such file), '/private/preboot/Cryptexes/OS/Users/mathew/Library/Developer/Xcode/DerivedData/SampleKeyboard-cwpdwgsjygjypaaaunncgzynbaby/Build/Products/Debug-iphoneos/PackageFrameworks/FleksyLibModule.framework/FleksyLibModule' (no such file), '/private/var/containers/Bundle/Application/6E41486B-B6CD-44CD-AFB9-18305781F16D/SampleKeyboard.app/PlugIns/SampleKeyboardApp.appex/Frameworks/FleksyLibModule.framework/FleksyLibModule' (no such file), '/private/var/containers/Bundle/Application/6E41486B-B6CD-44CD-AFB9-18305781F16D/SampleKeyboard.app/Frameworks/FleksyLibModule.framework/FleksyLibModule' (no such file), '/Users/mathew/Library/Developer/Xcode/DerivedData/SampleKeyboard-cwpdwgsjygjypaaaunncgzynbaby/Build/Products/Debug-iphoneos/PackageFrameworks/FleksyLibModule.framework/FleksyLibModule' (no such file), '/private/preboot/Cryptexes/OS/Users/mathew/Library/Developer/Xcode/DerivedData/SampleKeyboard-cwpdwgsjygjypaaaunncgzynbaby/Build/Products/Debug-iphoneos/PackageFrameworks/FleksyLibModule.framework/FleksyLibModule' (no such file), '/private/var/containers/Bundle/Application/6E41486B-B6CD-44CD-AFB9-18305781F16D/SampleKeyboard.app/PlugIns/SampleKeyboardApp.appex/Frameworks/FleksyLibModule.framework/FleksyLibModule' (no such file), '/private/var/containers/Bundle/Application/6E41486B-B6CD-44CD-AFB9-18305781F16D/SampleKeyboard.app/Frameworks/FleksyLibModule.framework/FleksyLibModule' (no such file)

**Comment by xevifar** [comment]
Hi @aswinjoseph91 , 

Please, could you download the repo: [predictiveSDK example](https://github.com/FleksySDK/PredictiveTextSDK/tree/main/Integration/PredictiveSDK-iOS) and compile it ? It should work for you. 
Regarding your project, you should try to clean your cache, reset package cache and make sure that the package is added like the example ? 

Best,

**Comment by subramanikios** [comment]
@xevifar ,

Thank you for your reply! I’ve gained more clarity and was able to run the app. Auto-corrections are working; however, I'm facing an issue where I keep receiving the same suggestion list even when I change the input text.

Here’s the suggestion list I'm getting:

`[
    FleksyLibModule.Candidate(
        type: FleksyLibModule.CandidateType.prediction,
        score: 0.0,
        replacements: [
            FleksyLibModule.Replacement(original: "", replacement: " ", start: 0, end: 0),
            FleksyLibModule.Replacement(original: "", replacement: "I", start: 0, end: 0)
        ]
    ),
    FleksyLibModule.Candidate(
        type: FleksyLibModule.CandidateType.prediction,
        score: 0.0,
        replacements: [
            FleksyLibModule.Replacement(original: "", replacement: " ", start: 0, end: 0),
            FleksyLibModule.Replacement(original: "", replacement: "I’m", start: 0, end: 0)
        ]
    ),
    FleksyLibModule.Candidate(
        type: FleksyLibModule.CandidateType.prediction,
        score: 0.0,
        replacements: [
            FleksyLibModule.Replacement(original: "", replacement: " ", start: 0, end: 0),
            FleksyLibModule.Replacement(original: "", replacement: "and", start: 0, end: 0)
        ]
    ),
    FleksyLibModule.Candidate(
        type: FleksyLibModule.CandidateType.prediction,
        score: 0.0,
        replacements: [
            FleksyLibModule.Replacement(original: "", replacement: " ", start: 0, end: 0),
            FleksyLibModule.Replacement(original: "", replacement: "is", start: 0, end: 0)
        ]
    ),
    FleksyLibModule.Candidate(
        type: FleksyLibModule.CandidateType.prediction,
        score: 0.0,
        replacements: [
            FleksyLibModule.Replacement(original: "", replacement: " ", start: 0, end: 0),
            FleksyLibModule.Replacement(original: "", replacement: "in", start: 0, end: 0)
        ]
    ),
    FleksyLibModule.Candidate(
        type: FleksyLibModule.CandidateType.prediction,
        score: 0.0,
        replacements: [
            FleksyLibModule.Replacement(original: "", replacement: " ", start: 0, end: 0),
            FleksyLibModule.Replacement(original: "", replacement: "I’ll", start: 0, end: 0)
        ]
    )
]
`

I receive this same list whenever I try the nextWordPrediction function, even with different input texts.

Steps I’ve completed:
1. Added the license key and secret key.
2. Using the same methods and functionality from the sample project.
I'm still confused as to why the suggestions remain the same. Any idea what might be causing this?

**Comment by xevifar** [comment]
Hi @subramanikios ,

It should work it out fine. See the video: 


https://github.com/user-attachments/assets/fa82924a-df71-4c84-9c63-257d2262fc86

You can check this file for the predictions: [PredictiveServiceManager](https://github.com/FleksySDK/PredictiveTextSDK/blob/main/Integration/PredictiveSDK-iOS/PredictiveSDKSample/Managers/PredictiveService/PredictiveServiceManager.swift)
